# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# Last updated: 20230623:22:32

name: Build and deploy container app to Azure Web App - variamos-ms-languages-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: ${{vars.ACR}}
        username: ${{secrets.ACRUSERNAME}}
        password: ${{secrets.ACRUSERPASSWORD}}

    - name: Build Docker image
      env: 
        NODE_ENV: production
        PORT: 4000
        DB_HOST: ${{secrets.PDN_DB_HOST}}
        DB_DATABASE: ${{secrets.PDB_DB_DATABASE}} 
        DB_PORT: ${{secrets.PDN_DB_PORT}} 
        DB_SSL: ${{secrets.PDN_DB_SSL}} 
        DB_USER: ${{secrets.PDN_DB_USER}} 
        DB_PASSWORD: ${{secrets.PDN_DB_PASSWORD}}
      run: docker build -t ${{vars.ACR}}/${{secrets.ACRUSERNAME}}/variamos_ms_languages:latest --build-arg NODE_ENV=${NODE_ENV} PORT=${PORT} $DB_HOST=${DB_HOST} DB_DATABASE=${DB_DATABASE} DB_PORT=${DB_PORT} DB_SSL=${DB_SSL} DB_USER=${DB_USER} DB_PASSWORD=${DB_PASSWORD} .
    
    - name: Push Docker image
      run: docker push ${{vars.ACR}}/${{secrets.ACRUSERNAME}}/variamos_ms_languages:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'variamos-ms-languages-2023'
        slot-name: 'production'
        publish-profile: ${{secrets.PRODUCTIONSLOTPUBLISHPROFILE}}
        images: '${{vars.ACR}}/${{secrets.ACRUSERNAME}}/variamos_ms_languages:latest'